title: One Line to Rule Them All
description: "一句顶一万句"
theme: just-the-docs

url: https://ME-Msc.github.io/One-Line-to-Rule-Them-All

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
